name: "{{ project_id_tgt }}.{{ marketing_googleads_datasets_reporting }}.KeywordStats"
description: "Keywords metrics."
fields:
  - name: "segments"
    description: "Segments details."
  - name: "segments.date"
    description: "Date to which metrics apply."
  - name: "keyword_view"
    description: "Keyword details."
  - name: "keyword_view.resource_name"
    description: "The resource name of the keyword view. Keyword view resource names have the form: customers/{customer_id}/keywordViews/{ad_group_id}~{criterion_id}"
  - name: "customer"
    description: "Customer details."
  - name: "customer.id"
    description: "The ID of the customer"
  - name: "customer.resource_name"
    description: "The resource name of the customer."
  - name: "customer.descriptive_name"
    description: "Optional, non-unique descriptive name of the customer"
  - name: "customer.status"
    description: "The status of the customer."
  - name: "campaign"
    description: "Campaign details."
  - name: "campaign.resource_name"
    description: "The resource name of the campaign."
  - name: "campaign.id"
    description: "The ID of the campaign"
  - name: "campaign.name"
    description: "The name of the campaign."
  - name: "campaign.status"
    description: "The status of the campaign. When a new campaign is added, the status defaults to ENABLED."
  - name: "campaign.start_date"
    description: "The date when campaign started in serving customer's timezone in YYYY-MM-DD format."
  - name: "campaign.end_date"
    description: "The last day of the campaign in serving customer's timezone in YYYY-MM-DD format."
  - name: "ad_group"
    description: "Ad Group details."
  - name: "ad_group.resource_name"
    description: "The resource name of the ad group."
  - name: "ad_group.id"
    description: "The ID of the ad group."
  - name: "ad_group.name"
    description: "The name of the ad group. This field is required and should not be empty when creating new ad groups."
  - name: "ad_group.status"
    description: "The status of the ad group."
  - name: "ad_group.campaign"
    description: "The campaign to which the ad group belongs."
  - name: "ad_group.type"
    description: "The type of the ad group."
  - name: "ad_group_criterion"
    description: "Ad Group Criterion detail."
  - name: "ad_group_criterion.resource_name"
    description: "The resource name of the ad group criterion."
  - name: "ad_group_criterion.criterion_id"
    description: "The ID of the criterion."
  - name: "ad_group_criterion.display_name"
    description: "The display name of the criterion"
  - name: "ad_group_criterion.ad_group"
    description: "The ad group to which the criterion belongs."
  - name: "ad_group_criterion.type"
    description: "The type of the criterion."
  - name: "ad_group_criterion.status"
    description: "The status of the criterion."
  - name: "ad_group_criterion.keyword"
    description: "Ad Group Criterion Keyword."
  - name: "ad_group_criterion.text"
    description: "The text of the keyword (at most 80 characters and 10 words)."
  - name: "ad_group_criterion.match_type"
    description: "The match type of the keyword."
  - name: "ad_group_criterion.quality_info"
    description: "Quality info."
  - name: "ad_group_criterion.quality_score"
    description: "The quality score. This field may not be populated if Google does not have enough information to determine a value."
  - name: "metrics"
    description: "Various metrics."
  - name: "metrics.clicks"
    description: "The number of clicks."
  - name: "metrics.average_cpc"
    description: "The total cost of all clicks divided by the total number of clicks received."
  - name: "metrics.all_conversions"
    description: "The total number of conversions. This includes all conversions regardless of the value of include_in_conversions_metric."
  - name: "metrics.cost_per_conversion"
    description: "The cost of ad interactions divided by conversions. This only includes conversion actions which include_in_conversions_metric attribute is set to true."
  - name: "metrics.search_impression_share"
    description: "The impressions you've received on the Search Network divided by the estimated number of impressions you were eligible to receive."
  - name: "metrics.active_view_measurable_cost_micros"
    description: "The cost of the impressions you received that were measurable by Active View."
  - name: "metrics.all_conversions_value_per_cost"
    description: "The value of all conversions divided by the total cost of ad interactions (such as clicks for text ads or views for video ads)."
  - name: "metrics.average_cost"
    description: "The average amount you pay per interaction. This amount is the total cost of your ads divided by the total number of interactions."
  - name: "metrics.conversions_value_per_cost"
    description: "The value of conversions divided by the cost of ad interactions."
  - name: "metrics.cost_micros"
    description: "The sum of your cost-per-click (CPC) and cost-per-thousand impressions (CPM) costs during this period."
  - name: "metrics.cost_per_all_conversions"
    description: "The cost of ad interactions divided by all conversions."
  - name: "metrics.cost_per_current_model_attributed_conversion"
    description: "The cost of ad interactions divided by current model attributed conversions."
  - name: "recordstamp"
    description: "Data load date and time"
