name: "{{ project_id_tgt }}.{{ marketing_googleads_datasets_reporting }}.KeywordsDailyAgg"
description: "Keywords metrics aggregated by date."
fields:
  - name: "report_date"
    description: "Report Date."
  - name: "criterion_id"
    description: "The ID of the criterion."
  - name: "keyword"
    description: "Keyword."
  - name: "match_type"
    description: "The match type of the keyword."
  - name: "keyword_status"
    description: "The status of the criterion."
  - name: "customer_id"
    description: "The ID of the customer."
  - name: "customer_name"
    description: "Non-unique descriptive name of the customer."
  - name: "customer_status"
    description: "The status of the customer."
  - name: "currency_code"
    description: "The currency in which the account operates."
  - name: "customer_time_zone"
    description: "The local timezone ID of the customer."
  - name: "campaign_id"
    description: "The ID of the campaign."
  - name: "campaign_name"
    description: "The name of the campaign."
  - name: "campaign_start_date"
    description: "The date when campaign started in serving customer's timezone in YYYY-MM-DD format."
  - name: "campaign_end_date"
    description: "The last day of the campaign in serving customer's timezone in YYYY-MM-DD format."
  - name: "adgroup_id"
    description: "The ID of the ad group."
  - name: "ad_group"
    description: "The name of the ad group."
  - name: "quality_score"
    description: "The quality score."
  - name: "clicks"
    description: "The number of clicks."
  - name: "cost"
    description: "The sum of your cost-per-click (CPC) and cost-per-thousand impressions (CPM) costs during this period."
