name: "{{ project_id_tgt }}.{{ marketing_tiktok_datasets_reporting }}.AdPerformance"
description: "Tiktok Ad Performance at daily level. This view is built on top of CDC table."
fields:
  - name: "stat_time_day"
    description: "Date"
  - name: "advertiser_id"
    description: "Advertiser ID"
  - name: "campaign_id"
    description: "Campaign ID"
  - name: "adgroup_id"
    description: "Ad group ID"
  - name: "ad_id"
    description: "Ad ID"
  - name: "country_code"
    description: "Group by location code"
  - name: "campaign_name"
    description: "The name you used when you created the campaign."
  - name: "adgroup_name"
    description: "Ad group name"
  - name: "advertiser_name"
    description: "Advertiser Name"
  - name: "ad_name"
    description: "Ad name"
  - name: "aeo_type"
    description: "App Event Optimization Type"
  - name: "ad_text"
    description: "Ad title"
  - name: "image_mode"
    description: "Creative format.\n Enum values:\n IMAGE_MODE_LARGE: Image\n IMAGE_MODE_VIDEO: Video (16:9)\n IMAGE_MODE_VIDEO_SQUARE: Video (1:1)\n IMAGE_MODE_VIDEO_VERTICAL: Video (9:16)\n CAROUSEL_ADS: Carousel."
  - name: "gross_impressions"
    description: "Gross Impressions (Includes Invalid Impressions)  The number of times an ad was seen on screen, including invalid impressions."
  - name: "cost_per_1000_reached"
    description: "Cost per 1,000 people reached. The average cost to reach 1,000 unique users. This metric is estimated."
  - name: "real_time_conversion"
    description: "Real-time Conversions. The number of times your ad achieved an outcome, based on the objective and settings you selected. (The total count is based on when the conversion actually happened.)"
  - name: "real_time_cost_per_conversion"
    description: "Real-time CPA.\n The average amount of money you've spent on a conversion. (The total count is based on when the conversion actually happened.)"
  - name: "real_time_conversion_rate"
    description: "Real-time CVR (%).\n The percentage of results you received out of all the clicks of your ads. (The total count is based on when the conversion actually happened.)"
  - name: "result"
    description: "The number of times your ad achieved an outcome, based on the optimization goal you selected."
  - name: "cost_per_result"
    description: "The average cost for each result from your ads."
  - name: "result_rate"
    description: "The percentage of results you achieved out of all of the views/clicks on your ads."
  - name: "real_time_result"
    description: "The number of times your ad achieved an outcome, based on the optimization goal you selected."
  - name: "real_time_cost_per_result"
    description: "Real-time Cost Per Result."
  - name: "real_time_result_rate"
    description: "Real-time Result Rate (%)."
  - name: "is_smart_creative"
    description: "Whether the ad is a Smart Creative ad."
  - name: "video_watched_2s"
    description: "2-Second Video Views. The number of times your video played for at least 2 seconds. Replays will not be counted."
  - name: "video_watched_6s"
    description: "6-Second Video Views. The number of times your video played for at least 6 seconds, or completely played. Replays will not be counted."
  - name: "average_video_play"
    description: "Video Average Watch Time Per Video View. The average time your video was played per single video view, including any time spent replaying the video."
  - name: "average_video_play_per_user"
    description: "Video Average Watch Time Per Person. The average time your video was played per person, including any time spent replaying the video. This metric is estimated."
  - name: "video_views_p25"
    description: "Video Views at 25%. The number of times your video was played at 25% of its length. Replays will not be counted."
  - name: "video_views_p50"
    description: "Video Views at 50%. The number of times your video was played at 50% of its length. Replays will not be counted."
  - name: "video_views_p75"
    description: "Video Views at 75%. The number of times your video was played at 75% of its length. Replays will not be counted."
  - name: "video_views_p100"
    description: "Video Views at 100%. The number of times your video was played at 100% of its length. Replays will not be counted."
  - name: "engaged_view"
    description: "6-second views (Focused view).\n The number of times your video has been played at least 6 seconds, or received at least 1 engagement within 1 day of the user seeing a paid ad. Engagements to be measured: Likes, shares, follows, profile visits, clicks, hashtag clicks, music clicks, anchor clicks, and interactive add-ons activity clicks."
  - name: "profile_visits"
    description: "Paid Profile Visit.\n The number of profile visits the paid ad drove during the campaign. This metric is only for Spark Ads."
  - name: "profile_visits_rate"
    description: "Paid Profile Visit Rate.\n The rate of profile visits per impression the paid ad drove during the campaign. This metric is only for Spark Ads."
  - name: "spend"
    description: "The estimated total amount of money you've spent on your campaign, ad group or ad during its schedule."
  - name: "clicks_on_music_disc"
    description: "The number of clicks on the official music in your Spard Ads during the campaign."
  - name: "impressions"
    description: "The Number of times your ads were on screen."
  - name: "clicks"
    description: "The Number of clicks on your ads."
  - name: "ctr"
    description: "The percentage of times people saw your ad and performed a click."
  - name: "cpc"
    description: "The average amount of money you've spent on a click."
  - name: "cpm"
    description: "The average amount of money you've spent per 1,000 impressions."
  - name: "reach"
    description: "The Number of unique users who saw your ads at least once. This metric is estimated."
  - name: "frequency"
    description: "The number of times a unique user saw your ad."
  - name: "conversion"
    description: "The Number of times your ad achieved an outcome, based on the secondary goal you selected."
  - name: "video_play_actions"
    description: "The number of times your video starts to play. Replays will not be counted."
  - name: "likes"
    description: "The number of likes your video creative received within 1 day of a user seeing a paid ad."
  - name: "comments"
    description: "The number of comments your video creative received within 1 day of a user seeing a paid ad."
  - name: "shares"
    description: "The number of shares your video creative received within 1 day of a user seeing a paid ad."
  - name: "follows"
    description: "The number of new followers that were gained within 1 day of a user seeing a paid ad. This metric is only for Spark Ads."
  - name: "currency"
    description: "The currency code, e. g. USD."
  - name: "budget"
    description: "Ad group budget."
  - name: "campaign_budget"
    description: "Campaign budget."
  - name: "placement_type"
    description: "Placement type."
  - name: "smart_target"
    description: "Optimization goal."
  - name: "cost_per_conversion"
    description: "CPA.\n The average amount of money you've spent on a conversion.(The total count is calculated based on the time each ad impression occurred.)"
  - name: "conversion_rate"
    description: "CVR (%).\n The percentage of results you received out of all the clicks of your ads.(The total count is calculated based on the time each ad impression occurred.)"
  - name: "conversion_rate_v2"
    description: "The percentage of conversions from all impressions on your ads.\n (The total count is calculated based on the time each ad impression occurred.)"
  - name: "timezone"
    description: "Ad account time zone including GMT offset. For example, \"Etc/GMT\""
  - name: "display_timezone"
    description: "Timezone name in the format of \"Region/City\" (based on the TZ database name conventions. For example, \"Europe/London\""
