name: "{{ project_id_tgt }}.{{ dataset_reporting_tgt }}.financial_statement_initial_load"
catalog_tags:
  - display_name: "line_of_business"
    fields:
      - display_name: "group"
        value: "Finance"
