name: "{{ project_id_tgt }}.{{ dataset_reporting_tgt }}.AccountingDocumentsReceivable"
description: "This view stores the financial transactions with customer and company master data details. The granularity of this view is Client(System), company code, fiscal year, accounting document number and number of line item within accounting document."
catalog_tags:
  - display_name: "line_of_business"
    fields:
      - display_name: "group"
        value: "Finance"
      - display_name: "domain"
        value: "Accounts Receivable"
fields:
  - name: "Client_MANDT"
    description: "Client (Mandant), PK"
  - name: "CompanyCode_BUKRS"
    description: "Company Code, PK"
  - name: "FiscalYear_GJAHR"
    description: "Fiscal year, PK"
  - name: "AccountingDocumentNumber_BELNR"
    description: "Accounting document number, PK"
  - name: "NumberOfLineItemWithinAccountingDocument_BUZEI"
    description: "Number of line item within accounting document, PK"
  - name: "ExchangeRateType_KURST"
    description: "Exchange Rate Type"
  - name: "CompanyText_BUTXT"
    description: "Company name"
  - name: "CustomerNumber_KUNNR"
    description: "Customer number"
  - name: "NAME1_NAME1"
    description: "Customer name"
  - name: "Company_Country"
    description: "Country key"
  - name: "Company_City"
    description: "Company city"
  - name: "CountryKey_LAND1"
    description: "Country key"
  - name: "City_ORT01"
    description: "Customer city"
  - name: "CurrencyKey_WAERS"
    description: "Currency key"
  - name: "LocalCurrency_HWAER"
    description: "Local Currency"
  - name: "FiscalyearVariant_PERIV"
    description: "Fiscal Year variant"
  - name: "Period"
    description: "Fiscal year period for posting date"
  - name: "Current_Period"
    description: "Fiscal year period for current date"
  - name: "AccountType_KOART"
    description: "Account Type"
  - name: "PostingDateInTheDocument_BUDAT"
    description: "Posting date in the document"
  - name: "DocumentDateInDocument_BLDAT"
    description: "Document date in the document"
  - name: "InvoiceToWhichTheTransactionBelongs_REBZG"
    description: "Document number of the invoice to which the transaction belongs"
  - name: "BillingDocument_VBELN"
    description: "Billing Document"
  - name: "WrittenOffAmount_DMBTR"
    description: "Amount which is not paid by customer in net due period and after sometime it is written off by business"
  - name: "BadDebt_DMBTR"
    description: "Unfortunate cost incurred by business when customer is not able to pay the due amount even after due period"
  - name: "NetDueDate"
    description: "Date on which the actual payment is due"
  - name: "CashDiscountDate1"
    description: "Due date for Cash Discount 1"
  - name: "CashDiscountDate2"
    description: "Due date for Cash Discount 2"
  - name: "OpenAndNotDue"
    description: "Amount for open items for which due date is in future"
  - name: "ClearedAfterDueDate"
    description: "Amount for items cleared after due date"
  - name: "ClearedOnOrBeforeDueDate"
    description: "Amount for items cleared on or before due date"
  - name: "OpenAndOverDue"
    description: "Amount for open items which are due"
  - name: "DoubtfulReceivables"
    description: "Amount which is pending for long against customer and has potential to bad debt"
  - name: "DaysInArrear"
    description: "Number of days between current and net due date"
  - name: "AccountsReceivable"
    description: "Total amount that the company owes from its customers"
  - name: "Sales"
    description: "Total amount associated with sales of the company"
