name: "{{ project_id_tgt }}.{{ dataset_reporting_tgt }}.NetDueDateCalc"
catalog_tags:
  - display_name: "line_of_business"
    fields:
      - display_name: "group"
        value: "Finance"
      - display_name: "domain"
        value: "Accounts receivable"
