name: "{{ project_id_tgt }}.{{ dataset_reporting_tgt }}.PlantsMD"
description: "This view contains plants master data including name of plant, valuation area, location and other details. The granularity is Client(System) and Plant"
catalog_tags:
  - display_name: "line_of_business"
    fields:
      - display_name: "group"
        value: "Master Data"
fields:
  - name: "Client_MANDT"
    description: "Client (Mandant), PK"
  - name: "Plant_WERKS"
    description: "Plant, PK"
  - name: "Name_NAME1"
    description: "Name"
  - name: "ValuationArea_BWKEY"
    description: "Valuation Area"
  - name: "CustomerNumberOfPlant_KUNNR"
    description: "Customer Number Of Plant"
  - name: "VendorNumberOfPlant_LIFNR"
    description: "Vendor Number Of Plant"
  - name: "FactoryCalendarKey_FABKL"
    description: "Factory Calendar Key"
  - name: "Name2_NAME2"
    description: "Name2"
  - name: "StreetAndHouseNumber_STRAS"
    description: "Street And House Number"
  - name: "PoBox_PFACH"
    description: "Po Box"
  - name: "PostalCode_PSTLZ"
    description: "Postal Code"
  - name: "City_ORT01"
    description: "City of plant in the address"
  - name: "PurchasingOrganization_EKORG"
    description: "Purchasing Organization"
  - name: "SalesOrganizationForIntercompanyBilling_VKORG"
    description: "Sales Organization For Intercompany Billing"
  - name: "Indicator_BatchStatusManagementActive_CHAZV"
    description: "Indicator: batch status management active"
  - name: "Indicator_ConditionsAtPlantLevel_KKOWK"
    description: "Indicator: Conditions at plant level"
  - name: "Indicator_SourceListRequirement_KORDB"
    description: "Indicator: Source list requirement"
  - name: "ActivatingRequirementsPlanning_BEDPL"
    description: "Activating Requirements Planning"
  - name: "CountryKey_LAND1"
    description: "Country Key"
  - name: "Region_County__REGIO"
    description: "Region (State, Province, County)"
  - name: "CountyCode_COUNC"
    description: "County Code"
  - name: "CityCode_CITYC"
    description: "City Code"
  - name: "Address_ADRNR"
    description: "Address"
  - name: "MaintenancePlanningPlant_IWERK"
    description: "Maintenance Planning Plant"
  - name: "TaxJurisdiction_TXJCD"
    description: "Tax Jurisdiction"
  - name: "DistributionChannelForIntercompanyBilling_VTWEG"
    description: "Distribution Channel For Intercompany Billing"
  - name: "DivisionForIntercompanyBilling_SPART"
    description: "Division For Intercompany Billing"
  - name: "Language_SPRAS"
    description: "Language"
  - name: "SopPlant_WKSOP"
    description: "Sales and operation planning plant(Indicates a dummy plant used for planning purposes in SOP)"
  - name: "VarianceKey_AWSLS"
    description: "Variance Key"
  - name: "Indicator_BatchStatusManagementActive_CHAZV_OLD"
    description: "Indicator: batch status management active"
  - name: "PlantCategory_VLFKZ"
    description: "Plant Category"
  - name: "SalesDistrict_BZIRK"
    description: "Sales District"
  - name: "SupplyRegion__regionSupplied___ZONE1"
    description: "Supply Region"
  - name: "TaxIndicator_Plant__purchasing___TAXIW"
    description: "Tax Indicator: Plant (Purchasing)"
  - name: "TakeRegularVendorIntoAccount_BZQHL"
    description: "Take Regular Vendor Into Account"
  - name: "NumberOfDaysForFirstReminderexpediter_LET01"
    description: "Number Of Days For First Reminderexpediter"
  - name: "NumberOfDaysForSecondReminderexpediter_LET02"
    description: "Number Of Days For Second Reminderexpediter"
  - name: "NumberOfDaysForThirdReminderexpediter_LET03"
    description: "Number Of Days For Third Reminderexpediter"
  - name: "TextNameOf1stDunningOfVendorDeclarations_TXNAM_MA1"
    description: "Text Name Of1st Dunning Of Vendor Declarations"
  - name: "TextNameOfThe2ndDunningOfVendorDeclarations_TXNAM_MA2"
    description: "Text Name Of The2nd Dunning Of Vendor Declarations"
  - name: "TextNameOf3rdDunningOfVendorDeclarations_TXNAM_MA3"
    description: "Text Name Of3rd Dunning Of Vendor Declarations"
  - name: "NumberOfDaysForPoToleranceCompressInfoRecordsSu_BETOL"
    description: "Number Of Days For Po Tolerance Compress Info Records Su"
  - name: "BusinessPlace_J_1BBRANCH"
    description: "Business Place"
  - name: "RuleForDeterminingTheSalesAreaForStockTransfers_VTBFI"
    description: "Rule For Determining The Sales Area For Stock Transfers"
  - name: "DistributionProfileAtPlantLevel_FPRFW"
    description: "Distribution Profile At Plant Level"
  - name: "CentralArchivingMarkerForMasterRecord_ACHVM"
    description: "Central Archiving Marker For Master Record"
  - name: "BatchRecord_TypeOfDmsUsed_DVSART"
    description: "Batch Record: Type of DMS Used"
  - name: "NodeType_SupplyChainNetwork_NODETYPE"
    description: "Node type: supply chain network"
  - name: "StructureForNameFormation_NSCHEMA"
    description: "Structure For Name Formation"
  - name: "CostObjectControllingLinkingActive_PKOSA"
    description: "Cost Object Controlling Linking Active"
  - name: "UpdatingIsActiveForMixedCosting_MISCH"
    description: "Updating Is Active For Mixed Costing"
  - name: "UpdatingIsActiveInActualCosting_MGVUPD"
    description: "Updating Is Active In Actual Costing"
  - name: "ShippingPointreceivingPoint_VSTEL"
    description: "Shipping Point/receiving Point"
  - name: "UpdateOfActivityConsumptionInTheQuantityStructure_MGVLAUPD"
    description: "Update Of Activity Consumption In The Quantity Structure"
  - name: "ControlOfCreditOfCostCenters_MGVLAREVAL"
    description: "Control Of Credit Of Cost Centers"
  - name: "InvokeAddedFunctionSourceDeterminationViaAtp_SOURCING"
    description: "Invoke Added Function Source Determination Via Atp"
  - name: "StoreCategoryToDifferentiateStoreShop_STORETYPE"
    description: "Store Category To Differentiate Store Shop"
  - name: "SuperiorDepartmentStore_DEP_STORE"
    description: "Superior Department Store"
