name: "{{ project_id_tgt }}.{{ dataset_reporting_tgt }}.SalesOrderScheduleLine"
description: "This view gives detailed information for the Schedule Lines of a Sales Order Document item including the Quantities and Dates associated with deliveries of each schedule line, confirmation status, line numbers, etc. The granularity is Client(system), Sales Document number, Sales Document Item and Schedule Line number."
catalog_tags:
  - display_name: "line_of_business"
    fields:
      - display_name: "group"
        value: "Sales"
      - display_name: "domain"
        value: "Order to Cash"
fields:
  - name: "Client_MANDT"
    description: "Client (Mandant), PK"
  - name: "SalesDocument_VBELN"
    description: "Sales Document, PK"
  - name: "SalesDocumentItem_POSNR"
    description: "Sales Document Item, PK"
  - name: "ScheduleLineNumber_ETENR"
    description: "Schedule Line Number, PK"
  - name: "ScheduleLineCategory_ETTYP"
    description: "Schedule Line Category"
  - name: "ItemRelevantforDelivery_LFREL"
    description: "Item is Relevant for Delivery"
  - name: "ScheduleLineDate_EDATU"
    description: "Schedule Line Date"
  - name: "ArrivalTime_EZEIT"
    description: "Arrival Time"
  - name: "OrderQuantityInSalesUnits_WMENG"
    description: "Order Quantity In Sales Units"
  - name: "ConfirmedQuantity_BMENG"
    description: "Confirmed Quantity"
  - name: "SalesUnit_VRKME"
    description: "Sales Unit"
  - name: "RequiredQuantityForMatManagementInStockkeepingUnits_LMENG"
    description: "Required Quantity For Material Management In Stockkeeping Units"
  - name: "BaseUnitOfMeasure_MEINS"
    description: "Base Unit Of Measure"
  - name: "RequirementDate_BDDAT"
    description: "Requirement Date(deadline for procurement)"
  - name: "RequirementType_BDART"
    description: "Requirement Type"
  - name: "PlanningType_PLART"
    description: "Planning Type"
  - name: "BusinessDocumentNumber_VBELE"
    description: "Business Document Number"
  - name: "BusinessItemNumber_POSNE"
    description: "Business Item Number"
  - name: "ScheduleLine_ETENE"
    description: "Schedule Line"
  - name: "EarliestPossibleReservationDate_RSDAT"
    description: "Earliest Possible Reservation Date"
  - name: "MaintenanceRequest_IDNNR"
    description: "Maintenance Request"
  - name: "PurchaseRequisitionNumber_BANFN"
    description: "Purchase Requisition Number"
  - name: "OrderType_BSART"
    description: "Order Type(Purchasing)"
  - name: "PurchasingDocumentCategory_BSTYP"
    description: "Purchasing Document Category"
  - name: "ConfirmationStatusOfScheduleLine_WEPOS"
    description: "Confirmation Status Of Schedule Line"
  - name: "InvoiceReceiptIndicator_REPOS"
    description: "Invoice Receipt Indicator"
  - name: "ReturnDateForReturnablePackaging_LRGDT"
    description: "Return Date For Returnable Packaging"
  - name: "DateType_PRGRS"
    description: "Date Type(day, week, month, interval)"
  - name: "TransportationPlanningDate_TDDAT"
    description: "Transportation Planning Date"
  - name: "MaterialAvailabilityDate_MBDAT"
    description: "Material Staging/Availability Date"
  - name: "LoadingDate_LDDAT"
    description: "Loading Date"
  - name: "GoodsIssueDate_WADAT"
    description: "Goods Issue Date"
  - name: "CorrectedQuantityInSalesUnit_CMENG"
    description: "Corrected Quantity In Sales Unit"
  - name: "ScheduleLineBlockedForDelivery_LIFSP"
    description: "Schedule Line Blocked For Delivery"
  - name: "GroupDefinitionOfStructureData_GRSTR"
    description: "Group Definition Of Structure Data"
  - name: "RelType_ABART"
    description: "Release Type"
  - name: "ForecastDeliveryScheduleNumber_ABRUF"
    description: "Forecast Delivery Schedule Number"
  - name: "CommittedQuantity_ROMS1"
    description: "Committed Quantity"
  - name: "Size2_ROMS2"
    description: "Size 2"
  - name: "Size3_ROMS3"
    description: "Size 3"
  - name: "UnitOfMeasureForSizes1to3_ROMEI"
    description: "Unit Of Measure For Sizes 1 to 3"
  - name: "FormulaKey_RFORM"
    description: "Formula Key for Variable-Size Items"
  - name: "NumeratorForConversionOfSalesQuantityIntoSKU_UMVKZ"
    description: "Numerator (factor) for conversion of sales quantity into SKU"
  - name: "DenominatorForConversionOfSalesQtyIntoSKU_UMVKN"
    description: "Denominator (Divisor) for Conversion of Sales Quantity into SKU"
  - name: "AvailabilityConfirmedAutomatically_VERFP"
    description: "Availability Confirmed Automatically"
  - name: "MovementType_BWART"
    description: "Movement Type(Inventory management)"
  - name: "ItemNumberOfPurchaseRequisition_BNFPO"
    description: "Item Number Of Purchase Requisition"
  - name: "ScheduleLineTypeEDI_ETART"
    description: "Schedule Line Type EDI"
  - name: "OrderNumber_AUFNR"
    description: "Order Number"
  - name: "PlannedOrderNumber_PLNUM"
    description: "Planned Order Number"
  - name: "BOMExplosionNumber_SERNR"
    description: "BOM Explosion Number"
  - name: "CustomerEngineeringChangeStatus_AESKD"
    description: "Customer Engineering Change Status"
  - name: "Guaranteed_ABGES"
    description: "Guaranteed(factor between 0 and 1)"
  - name: "MaterialStagingTime_MBUHR"
    description: "Material Staging Time (Local, Relating to a Plant)"
  - name: "TranspPlanningTime_TDUHR"
    description: "Transp Planning Time (Local, Relating to a Shipping Point)"
  - name: "LoadingTime_LDUHR"
    description: "Loading Time (Local Time Relating to a Shipping Point)"
  - name: "TimeOfGoodsIssue_WAUHR"
    description: "Time Of Goods Issue (Local, Relating to a Plant)"
  - name: "RouteSchedule_AULWE"
    description: "Route Schedule"
  - name: "HandoverDateAtTheHandoverLocation_HANDOVERDATE"
    description: "Handover Date At The Handover Location"
  - name: "HandoverTimeAtTheHandoverLocation_HANDOVERTIME"
    description: "Handover Time At The Handover Location"
  - name: "DeliveryDateRule_DELIVERY_DATE_TYPE_RULE"
    description: "Delivery Date Type Rule"
  - name: "DeliveredQuantity_DLVQTY_BU"
    description: "Delivered Quantity"
  - name: "DeliveredQuantity_DLVQTY_SU"
    description: "Delivered Quantity"
  - name: "OpenConfirmedDeliveryQuantity_OCDQTY_BU"
    description: "Open Confirmed Delivery Quantity"
  - name: "OpenConfirmedDeliveryQuantity_OCDQTY_SU"
    description: "Open Confirmed Delivery Quantity"
  - name: "OpenRequestedDeliveryQuantity_ORDQTY_BU"
    description: "Open Requested Delivery Quantity"
  - name: "OpenRequestedDeliveryQuantity_ORDQTY_SU"
    description: "Open Requested Delivery Quantity"
  - name: "DeliveryCreationDate_CREA_DLVDATE"
    description: "Delivery Creation Date"
  - name: "ScheduleLineDate_REQ_DLVDATE"
    description: "Schedule Line Date"
  - name: "RequirementsClass_BEDAR"
    description: "Requirements Class"
  - name: "DataFilterValueForDataAging_DATAAGING"
    description: "Data Filter Value For Data Aging"
  - name: "SDDocumentCurrency_WAERK"
    description: "SD Document Currency"
  - name: "OpenDeliveryNetAmount_ODN_AMOUNT"
    description: "Open Delivery Net Amount(in Sales Document Currency)"
  - name: "GUIDInRAWFormat_HANDLE"
    description: "GUID In 'RAW' Format"
  - name: "LegalControlCheckStatus_LCCST"
    description: "Legal Control Check Status"
  - name: "RequestedRequirementQuantityInBaseUnit_RRQQTY_BU"
    description: "Requested Requirement Quantity In Base Unit"
  - name: "ConfirmedRequirementQuantityInBaseUnit_CRQQTY_BU"
    description: "Confirmed Requirement Quantity In Base Unit"
  - name: "DummyFunctionInLength1_DUMMY_SLSDOCSCHEDL_INCL_EEW_PS"
    description: "Dummy Function In Length 1"
  - name: "ARunRequirementAllocatedQuantity_FSH_RALLOC_QTY"
    description: "ARun Requirement Allocated Quantity"
  - name: "OrderSchedulingGroupID_FSH_OS_ID"
    description: "Order Scheduling Group ID"
  - name: "RejectionCodeForPartialQuantityRejection_FSH_PQR_RC"
    description: "Rejection Code For Partial Quantity Rejection"
  - name: "MaterialAvailabilityDateThirdPartyOrderPlanning_MBDAT_DRS"
    description: "Material Availability Date Third Party Order Planning"
  - name: "YearOfChangeDate_EDATU"
    description: "Year Of Schedule Line Date"
  - name: "MonthOfChangeDate_EDATU"
    description: "Month Of Schedule Line Date"
  - name: "WeekOfChangeDate_EDATU"
    description: "Week Of Schedule Line Date"
  - name: "QuarterOfChangeDate_EDATU"
    description: "Quarter Of Schedule Line Date"
