name: "{{ project_id_tgt }}.{{ dataset_reporting_tgt }}.StockInHand"
description: "This view calculates the aggregated unrestricted stock quantity from various sources / locations, including distribution centers, vendor locations, customer Locations, and special stocks at Vendor in Consignment. This view has a granularity of Client(system), material number, plant, storage location, batch number, special stock indicator, SD document number and item, vendor and customer number."
catalog_tags:
  - display_name: "line_of_business"
    fields:
      - display_name: "group"
        value: "Supply Chain"
      - display_name: "domain"
        value: "Inventory Management"
fields:
  - name: "Client_MANDT"
    description: "Client (Mandant), PK"
  - name: "MaterialNumber_MATNR"
    description: "Material Number, PK"
  - name: "Plant_WERKS"
    description: "Plant, PK"
  - name: "ArticleNumber_MATNR"
    description: "Deprecated. Use MaterialNumber_MATNR instead."
  - name: "Site_WERKS"
    description: "Deprecated. Use Plant_WERKS instead."
  - name: "StorageLocation_LGORT"
    description: "Storage Location, PK"
  - name: "BatchNumber_CHARG"
    description: "Batch Number, PK"
  - name: "SpecialStockIndicator_SOBKZ"
    description: "Special Stock Indicator, PK"
  - name: "SDDocumentNumber_VBELN"
    description: "Sales and Delivery Document Number, PK"
  - name: "SDDocumentItemNumber_POSNR"
    description: "Item Number of Sales and Delivery Document, PK"
  - name: "VendorAccountNumber_LIFNR"
    description: "Account Number of Vendor or Creditor, PK"
  - name: "CustomerNumber_KUNNR"
    description: "Customer Number, PK"
  - name: "Qty"
    description: "Stock in Hand Quantity"
  - name: "StockType"
    description: "Stock Type"
